
name: jtaer-repl
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - statsmodels
  - linearmodels
  - scikit-learn
  - pyarrow
  - matplotlib
  - pytest
  - pip
  - pip:
      - pandera
      - ruff
